/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: krml /workspace/DeadlineModel.fst -tmpdir /tmp/c_out -skip-compilation -warn-error -2
  F* version: <unknown>
  KaRaMeL version: 3611ae497bb5ab8ae83207428c8a915653bd761c
 */

#ifndef internal_Prims_H
#define internal_Prims_H

#include "krmllib.h"

extern krml_checked_int_t Prims_op_Division(krml_checked_int_t x, krml_checked_int_t y);

extern krml_checked_int_t Prims_op_Subtraction(krml_checked_int_t x, krml_checked_int_t y);

extern krml_checked_int_t Prims_op_Addition(krml_checked_int_t x, krml_checked_int_t y);

extern krml_checked_int_t Prims_op_Minus(krml_checked_int_t x0);

extern bool Prims_op_LessThanOrEqual(krml_checked_int_t x0, krml_checked_int_t x1);

extern bool Prims_op_GreaterThan(krml_checked_int_t x0, krml_checked_int_t x1);

extern bool Prims_op_GreaterThanOrEqual(krml_checked_int_t x0, krml_checked_int_t x1);

extern bool Prims_op_LessThan(krml_checked_int_t x0, krml_checked_int_t x1);


#define internal_Prims_H_DEFINED
#endif /* internal_Prims_H */
