/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: krml /workspace/TauFairScheduler.fst -tmpdir /tmp/c_out -skip-compilation -warn-error -2
  F* version: <unknown>
  KaRaMeL version: 3611ae497bb5ab8ae83207428c8a915653bd761c
 */

#include "internal/TauFairScheduler.h"

#include "internal/Prims.h"

krml_checked_int_t
TauFairScheduler_mul(krml_checked_int_t a, krml_checked_int_t b, krml_checked_int_t acc)
{
  if (Prims_op_LessThanOrEqual(b, 0))
    return acc;
  else
    return TauFairScheduler_mul(a, Prims_op_Subtraction(b, 1), Prims_op_Addition(acc, a));
}

static krml_checked_int_t hd__krml_checked_int_t(Prims_list__krml_checked_int_t *uu___)
{
  if (uu___->tag == Prims_Cons)
    return uu___->hd;
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

static Prims_list__krml_checked_int_t
*tail__krml_checked_int_t(Prims_list__krml_checked_int_t *uu___)
{
  if (uu___->tag == Prims_Cons)
    return uu___->tl;
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

static Prims_list__krml_checked_int_t
*(*tl__krml_checked_int_t)(Prims_list__krml_checked_int_t *x0) = tail__krml_checked_int_t;

krml_checked_int_t
FStar_List_Tot_Base_index__krml_checked_int_t(
  Prims_list__krml_checked_int_t *l,
  krml_checked_int_t i
)
{
  if (i == 0)
    return hd__krml_checked_int_t(l);
  else
    return
      FStar_List_Tot_Base_index__krml_checked_int_t(tl__krml_checked_int_t(l),
        Prims_op_Subtraction(i, 1));
}

static krml_checked_int_t
index__krml_checked_int_t(Prims_list__krml_checked_int_t *s, krml_checked_int_t i)
{
  return FStar_List_Tot_Base_index__krml_checked_int_t(s, i);
}

bool
TauFairScheduler_would_violate_aux(
  Prims_list__krml_checked_int_t *running_deadlines_us,
  krml_checked_int_t threshold,
  krml_checked_int_t i,
  krml_checked_int_t n_running
)
{
  if (Prims_op_GreaterThanOrEqual(i, n_running))
    return false;
  else if
  (Prims_op_LessThanOrEqual(index__krml_checked_int_t(running_deadlines_us, i), threshold))
    return true;
  else
    return
      TauFairScheduler_would_violate_aux(running_deadlines_us,
        threshold,
        Prims_op_Addition(i, 1),
        n_running);
}

static Prims_list__krml_checked_int_t *empty__krml_checked_int_t(void)
{
  Prims_list__krml_checked_int_t
  *buf = KRML_HOST_MALLOC(sizeof (Prims_list__krml_checked_int_t));
  if (buf != NULL)
    buf[0U] = ((Prims_list__krml_checked_int_t){ .tag = Prims_Nil });
  return buf;
}

Prims_list__krml_checked_int_t
*FStar_List_Tot_Base_append__krml_checked_int_t(
  Prims_list__krml_checked_int_t *x,
  Prims_list__krml_checked_int_t *y
)
{
  if (x->tag == Prims_Nil)
    return y;
  else if (x->tag == Prims_Cons)
  {
    Prims_list__krml_checked_int_t *tl1 = x->tl;
    krml_checked_int_t a1 = x->hd;
    Prims_list__krml_checked_int_t
    *buf = KRML_HOST_MALLOC(sizeof (Prims_list__krml_checked_int_t));
    if (buf != NULL)
      buf[0U] =
        (
          (Prims_list__krml_checked_int_t){
            .tag = Prims_Cons,
            .hd = a1,
            .tl = FStar_List_Tot_Base_append__krml_checked_int_t(tl1, y)
          }
        );
    return buf;
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

static Prims_list__krml_checked_int_t
*append__krml_checked_int_t(
  Prims_list__krml_checked_int_t *s1,
  Prims_list__krml_checked_int_t *s2
)
{
  return FStar_List_Tot_Base_append__krml_checked_int_t(s1, s2);
}

static Prims_list__krml_checked_int_t
*_cons__krml_checked_int_t(krml_checked_int_t x, Prims_list__krml_checked_int_t *s)
{
  Prims_list__krml_checked_int_t
  *buf = KRML_HOST_MALLOC(sizeof (Prims_list__krml_checked_int_t));
  if (buf != NULL)
    buf[0U] = ((Prims_list__krml_checked_int_t){ .tag = Prims_Cons, .hd = x, .tl = s });
  return buf;
}

Prims_list__krml_checked_int_t
*FStar_Seq_Base_create__krml_checked_int_t(krml_checked_int_t len, krml_checked_int_t v)
{
  if (len == 0)
  {
    Prims_list__krml_checked_int_t
    *buf = KRML_HOST_MALLOC(sizeof (Prims_list__krml_checked_int_t));
    if (buf != NULL)
      buf[0U] = ((Prims_list__krml_checked_int_t){ .tag = Prims_Nil });
    return buf;
  }
  else
    return
      _cons__krml_checked_int_t(v,
        FStar_Seq_Base_create__krml_checked_int_t(Prims_op_Subtraction(len, 1), v));
}

static Prims_list__krml_checked_int_t
*cons__krml_checked_int_t(krml_checked_int_t x, Prims_list__krml_checked_int_t *s)
{
  return append__krml_checked_int_t(FStar_Seq_Base_create__krml_checked_int_t(1, x), s);
}

Prims_list__krml_checked_int_t
*TauFairScheduler_gen_range(krml_checked_int_t n, krml_checked_int_t i)
{
  if (Prims_op_GreaterThanOrEqual(i, n))
    return empty__krml_checked_int_t();
  else
    return cons__krml_checked_int_t(i, TauFairScheduler_gen_range(n, Prims_op_Addition(i, 1)));
}

krml_checked_int_t
FStar_List_Tot_Base_length__krml_checked_int_t(Prims_list__krml_checked_int_t *uu___)
{
  if (uu___->tag == Prims_Nil)
    return 0;
  else if (uu___->tag == Prims_Cons)
  {
    Prims_list__krml_checked_int_t *tl1 = uu___->tl;
    return Prims_op_Addition(1, FStar_List_Tot_Base_length__krml_checked_int_t(tl1));
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

static krml_checked_int_t length__krml_checked_int_t(Prims_list__krml_checked_int_t *s)
{
  return FStar_List_Tot_Base_length__krml_checked_int_t(s);
}

static krml_checked_int_t head__krml_checked_int_t(Prims_list__krml_checked_int_t *s)
{
  return index__krml_checked_int_t(s, 0);
}

static Prims_list__krml_checked_int_t
*tl__krml_checked_int_t0(Prims_list__krml_checked_int_t *s)
{
  return tl__krml_checked_int_t(s);
}

static krml_checked_int_t hd__krml_checked_int_t0(Prims_list__krml_checked_int_t *s)
{
  return hd__krml_checked_int_t(s);
}

Prims_list__krml_checked_int_t
*FStar_Seq_Base_slice___krml_checked_int_t(
  Prims_list__krml_checked_int_t *s,
  krml_checked_int_t i,
  krml_checked_int_t j
)
{
  if (Prims_op_GreaterThan(i, 0))
    return
      FStar_Seq_Base_slice___krml_checked_int_t(tl__krml_checked_int_t0(s),
        Prims_op_Subtraction(i, 1),
        Prims_op_Subtraction(j, 1));
  else if (j == 0)
  {
    Prims_list__krml_checked_int_t
    *buf = KRML_HOST_MALLOC(sizeof (Prims_list__krml_checked_int_t));
    if (buf != NULL)
      buf[0U] = ((Prims_list__krml_checked_int_t){ .tag = Prims_Nil });
    return buf;
  }
  else
    return
      _cons__krml_checked_int_t(hd__krml_checked_int_t0(s),
        FStar_Seq_Base_slice___krml_checked_int_t(tl__krml_checked_int_t0(s),
          i,
          Prims_op_Subtraction(j, 1)));
}

static Prims_list__krml_checked_int_t
*(*slice__krml_checked_int_t)(
  Prims_list__krml_checked_int_t *x0,
  krml_checked_int_t x1,
  krml_checked_int_t x2
) = FStar_Seq_Base_slice___krml_checked_int_t;

static Prims_list__krml_checked_int_t
*tail__krml_checked_int_t0(Prims_list__krml_checked_int_t *s)
{
  return slice__krml_checked_int_t(s, 1, length__krml_checked_int_t(s));
}

Prims_list__krml_checked_int_t
*TauFairScheduler_remove_elem(Prims_list__krml_checked_int_t *s, krml_checked_int_t v)
{
  if (length__krml_checked_int_t(s) == 0)
    return empty__krml_checked_int_t();
  else
  {
    krml_checked_int_t hd = head__krml_checked_int_t(s);
    Prims_list__krml_checked_int_t *tl = tail__krml_checked_int_t0(s);
    if (hd == v)
      return tl;
    else
      return cons__krml_checked_int_t(hd, TauFairScheduler_remove_elem(tl, v));
  }
}

krml_checked_int_t
TauFairScheduler_warn_overdue_aux(
  Prims_list__krml_checked_int_t *deadlines_us,
  krml_checked_int_t n,
  krml_checked_int_t now_us,
  krml_checked_int_t i
)
{
  if (Prims_op_GreaterThanOrEqual(i, n))
    return 0;
  else
  {
    krml_checked_int_t ite;
    if (Prims_op_LessThanOrEqual(index__krml_checked_int_t(deadlines_us, i), now_us))
      ite = 1;
    else
      ite = 0;
    return
      Prims_op_Addition(ite,
        TauFairScheduler_warn_overdue_aux(deadlines_us, n, now_us, Prims_op_Addition(i, 1)));
  }
}

krml_checked_int_t
TauFairScheduler_count_prefill_aux(
  Prims_list__krml_checked_int_t *total_kvs,
  Prims_list__krml_checked_int_t *fair_shares,
  krml_checked_int_t n,
  krml_checked_int_t i
)
{
  if (Prims_op_GreaterThanOrEqual(i, n))
    return 0;
  else
  {
    krml_checked_int_t ite;
    if
    (
      Prims_op_LessThanOrEqual(index__krml_checked_int_t(total_kvs, i),
        index__krml_checked_int_t(fair_shares, i))
    )
      ite = 1;
    else
      ite = 0;
    return
      Prims_op_Addition(ite,
        TauFairScheduler_count_prefill_aux(total_kvs, fair_shares, n, Prims_op_Addition(i, 1)));
  }
}

Prims_list__krml_checked_int_t
*FStar_Seq_Base_upd___krml_checked_int_t(
  Prims_list__krml_checked_int_t *s,
  krml_checked_int_t n,
  krml_checked_int_t v
)
{
  if (n == 0)
    return _cons__krml_checked_int_t(v, tl__krml_checked_int_t0(s));
  else
    return
      _cons__krml_checked_int_t(hd__krml_checked_int_t0(s),
        FStar_Seq_Base_upd___krml_checked_int_t(tl__krml_checked_int_t0(s),
          Prims_op_Subtraction(n, 1),
          v));
}

static Prims_list__krml_checked_int_t
*(*upd__krml_checked_int_t)(
  Prims_list__krml_checked_int_t *x0,
  krml_checked_int_t x1,
  krml_checked_int_t x2
) = FStar_Seq_Base_upd___krml_checked_int_t;

Prims_list__krml_checked_int_t
*TauFairScheduler_check_decode_deadlines_aux(
  Prims_list__krml_checked_int_t *deadlines_us,
  krml_checked_int_t n,
  krml_checked_int_t now_us,
  krml_checked_int_t i,
  Prims_list__krml_checked_int_t *acc
)
{
  if (Prims_op_GreaterThanOrEqual(i, n))
    return acc;
  else
  {
    krml_checked_int_t flag;
    if (Prims_op_LessThanOrEqual(index__krml_checked_int_t(deadlines_us, i), now_us))
      flag = 1;
    else
      flag = 0;
    return
      TauFairScheduler_check_decode_deadlines_aux(deadlines_us,
        n,
        now_us,
        Prims_op_Addition(i, 1),
        upd__krml_checked_int_t(acc, i, flag));
  }
}

krml_checked_int_t
TauFairScheduler_sum_aux(
  Prims_list__krml_checked_int_t *total_kvs,
  krml_checked_int_t n,
  krml_checked_int_t i
)
{
  if (Prims_op_GreaterThanOrEqual(i, n))
    return 0;
  else
    return
      Prims_op_Addition(index__krml_checked_int_t(total_kvs, i),
        TauFairScheduler_sum_aux(total_kvs, n, Prims_op_Addition(i, 1)));
}

TauFairScheduler_e_d_f_ordering_key
TauFairScheduler_edf_fairshare_key(
  krml_checked_int_t deadline_us,
  krml_checked_int_t total_kv,
  krml_checked_int_t fair_share,
  krml_checked_int_t tau_us,
  krml_checked_int_t now_us
)
{
  krml_checked_int_t tier;
  if (Prims_op_LessThanOrEqual(deadline_us, now_us))
    tier = 0;
  else if (Prims_op_LessThanOrEqual(Prims_op_Subtraction(deadline_us, now_us), tau_us))
    tier = 1;
  else
    tier = 2;
  krml_checked_int_t shortfall;
  if (Prims_op_GreaterThan(fair_share, total_kv))
    shortfall = Prims_op_Subtraction(fair_share, total_kv);
  else
    shortfall = 0;
  krml_checked_int_t excess;
  if (Prims_op_GreaterThan(total_kv, fair_share))
    excess = Prims_op_Subtraction(total_kv, fair_share);
  else
    excess = 0;
  return
    (
      (TauFairScheduler_e_d_f_ordering_key){
        .tier = tier,
        .neg_shortfall = Prims_op_Minus(shortfall),
        .excess = excess
      }
    );
}

bool
TauFairScheduler_edf_compare(
  TauFairScheduler_e_d_f_ordering_key a,
  TauFairScheduler_e_d_f_ordering_key b
)
{
  if (a.tier != b.tier)
    return Prims_op_LessThan(a.tier, b.tier);
  else if (a.neg_shortfall != b.neg_shortfall)
    return Prims_op_LessThan(a.neg_shortfall, b.neg_shortfall);
  else
    return Prims_op_LessThan(a.excess, b.excess);
}

bool
TauFairScheduler_is_well_behaved(krml_checked_int_t total_kv, krml_checked_int_t fair_share)
{
  return Prims_op_LessThanOrEqual(total_kv, fair_share);
}

bool TauFairScheduler_is_over_quota(krml_checked_int_t total_kv, krml_checked_int_t fair_share)
{
  return Prims_op_GreaterThan(total_kv, fair_share);
}

bool
TauFairScheduler_is_within_reservation(
  krml_checked_int_t total_kv,
  krml_checked_int_t reservation
)
{
  return Prims_op_LessThanOrEqual(total_kv, reservation);
}

krml_checked_int_t
TauFairScheduler_unevictable_tokens(
  krml_checked_int_t total_kv,
  krml_checked_int_t evictable_kv
)
{
  return Prims_op_Subtraction(total_kv, evictable_kv);
}

krml_checked_int_t
TauFairScheduler_eviction_spare(krml_checked_int_t total_kv, krml_checked_int_t reservation)
{
  if (Prims_op_GreaterThan(total_kv, reservation))
    return Prims_op_Subtraction(total_kv, reservation);
  else
    return 0;
}

krml_checked_int_t
TauFairScheduler_on_new_request_init_deadline(
  TauFairScheduler_alt_history_state alt_state,
  Prims_string uid,
  krml_checked_int_t prompt_len,
  krml_checked_int_t completion_len,
  krml_checked_int_t iso_prefill_time_us,
  krml_checked_int_t tau_cache_us,
  krml_checked_int_t tau_prefill_us,
  krml_checked_int_t now_us
)
{
  KRML_MAYBE_UNUSED_VAR(alt_state);
  KRML_MAYBE_UNUSED_VAR(uid);
  KRML_MAYBE_UNUSED_VAR(prompt_len);
  KRML_MAYBE_UNUSED_VAR(completion_len);
  return
    Prims_op_Addition(Prims_op_Addition(Prims_op_Addition(now_us, iso_prefill_time_us),
        tau_cache_us),
      tau_prefill_us);
}

bool
TauFairScheduler_would_violate_decode_deadlines(
  TauFairScheduler_alt_history_state alt_state,
  krml_checked_int_t prefill_cost_us,
  krml_checked_int_t headroom_us,
  Prims_list__krml_checked_int_t *running_deadlines_us,
  krml_checked_int_t n_running,
  krml_checked_int_t delta_decode_mt_us,
  krml_checked_int_t now_us
)
{
  KRML_MAYBE_UNUSED_VAR(alt_state);
  KRML_MAYBE_UNUSED_VAR(headroom_us);
  krml_checked_int_t
  threshold = Prims_op_Addition(Prims_op_Addition(now_us, prefill_cost_us), delta_decode_mt_us);
  return TauFairScheduler_would_violate_aux(running_deadlines_us, threshold, 0, n_running);
}

krml_checked_int_t
TauFairScheduler_prefill_vs_decode_decision(
  TauFairScheduler_alt_history_state alt_state,
  Prims_list__krml_checked_int_t *running_deadlines_us,
  krml_checked_int_t n_running,
  bool has_candidate_prefill,
  krml_checked_int_t prefill_cost_us,
  krml_checked_int_t accumulated_headroom_us,
  krml_checked_int_t delta_decode_mt_us,
  krml_checked_int_t tau_us,
  krml_checked_int_t now_us,
  bool any_over_quota,
  bool any_starved,
  bool max_per_user_active
)
{
  KRML_MAYBE_UNUSED_VAR(tau_us);
  KRML_MAYBE_UNUSED_VAR(any_starved);
  if (!has_candidate_prefill)
    if (Prims_op_GreaterThan(n_running, 0))
      return -1;
    else
      return 0;
  else if
  (
    Prims_op_LessThanOrEqual(prefill_cost_us, accumulated_headroom_us) && !any_over_quota &&
      !max_per_user_active
    &&
      !TauFairScheduler_would_violate_decode_deadlines(alt_state,
        prefill_cost_us,
        accumulated_headroom_us,
        running_deadlines_us,
        n_running,
        delta_decode_mt_us,
        now_us)
  )
    return 1;
  else if (Prims_op_GreaterThan(n_running, 0))
    return -1;
  else
    return 0;
}

TauFairScheduler_e_d_f_ordering_key
TauFairScheduler_key_of(
  Prims_list__krml_checked_int_t *deadlines_us,
  Prims_list__krml_checked_int_t *total_kvs,
  Prims_list__krml_checked_int_t *fair_shares,
  krml_checked_int_t tau_us,
  krml_checked_int_t now_us,
  krml_checked_int_t i
)
{
  return
    TauFairScheduler_edf_fairshare_key(index__krml_checked_int_t(deadlines_us, i),
      index__krml_checked_int_t(total_kvs, i),
      index__krml_checked_int_t(fair_shares, i),
      tau_us,
      now_us);
}

krml_checked_int_t
TauFairScheduler_find_min(
  Prims_list__krml_checked_int_t *deadlines_us,
  Prims_list__krml_checked_int_t *total_kvs,
  Prims_list__krml_checked_int_t *fair_shares,
  krml_checked_int_t tau_us,
  krml_checked_int_t now_us,
  Prims_list__krml_checked_int_t *s
)
{
  if (length__krml_checked_int_t(s) == 1)
    return head__krml_checked_int_t(s);
  else
  {
    krml_checked_int_t hd = head__krml_checked_int_t(s);
    Prims_list__krml_checked_int_t *tl = tail__krml_checked_int_t0(s);
    krml_checked_int_t
    rest = TauFairScheduler_find_min(deadlines_us, total_kvs, fair_shares, tau_us, now_us, tl);
    if
    (
      TauFairScheduler_edf_compare(TauFairScheduler_key_of(deadlines_us,
          total_kvs,
          fair_shares,
          tau_us,
          now_us,
          hd),
        TauFairScheduler_key_of(deadlines_us, total_kvs, fair_shares, tau_us, now_us, rest))
    )
      return hd;
    else
      return rest;
  }
}

static Prims_list__krml_checked_int_t
*snoc__krml_checked_int_t(Prims_list__krml_checked_int_t *s, krml_checked_int_t x)
{
  return append__krml_checked_int_t(s, FStar_Seq_Base_create__krml_checked_int_t(1, x));
}

Prims_list__krml_checked_int_t
*TauFairScheduler_sort_aux(
  Prims_list__krml_checked_int_t *deadlines_us,
  Prims_list__krml_checked_int_t *total_kvs,
  Prims_list__krml_checked_int_t *fair_shares,
  krml_checked_int_t tau_us,
  krml_checked_int_t now_us,
  Prims_list__krml_checked_int_t *s,
  Prims_list__krml_checked_int_t *acc
)
{
  if (length__krml_checked_int_t(s) == 0)
    return acc;
  else
  {
    krml_checked_int_t
    m = TauFairScheduler_find_min(deadlines_us, total_kvs, fair_shares, tau_us, now_us, s);
    return
      TauFairScheduler_sort_aux(deadlines_us,
        total_kvs,
        fair_shares,
        tau_us,
        now_us,
        TauFairScheduler_remove_elem(s, m),
        snoc__krml_checked_int_t(acc, m));
  }
}

Prims_list__krml_checked_int_t
*TauFairScheduler_sort_prefill_queue(
  TauFairScheduler_alt_history_state alt_state,
  Prims_list__krml_checked_int_t *deadlines_us,
  Prims_list__Prims_string *uids,
  Prims_list__krml_checked_int_t *total_kvs,
  Prims_list__krml_checked_int_t *fair_shares,
  krml_checked_int_t n,
  krml_checked_int_t tau_us,
  krml_checked_int_t now_us
)
{
  KRML_MAYBE_UNUSED_VAR(alt_state);
  KRML_MAYBE_UNUSED_VAR(uids);
  return
    TauFairScheduler_sort_aux(deadlines_us,
      total_kvs,
      fair_shares,
      tau_us,
      now_us,
      TauFairScheduler_gen_range(n, 0),
      empty__krml_checked_int_t());
}

krml_checked_int_t
TauFairScheduler_warn_overdue_deadlines(
  TauFairScheduler_alt_history_state alt_state,
  Prims_list__krml_checked_int_t *deadlines_us,
  krml_checked_int_t n,
  krml_checked_int_t now_us
)
{
  KRML_MAYBE_UNUSED_VAR(alt_state);
  return TauFairScheduler_warn_overdue_aux(deadlines_us, n, now_us, 0);
}

krml_checked_int_t
TauFairScheduler_count_prefill_admitted(
  TauFairScheduler_alt_history_state alt_state,
  Prims_list__Prims_string *uids,
  Prims_list__krml_checked_int_t *total_kvs,
  Prims_list__krml_checked_int_t *fair_shares,
  krml_checked_int_t n
)
{
  KRML_MAYBE_UNUSED_VAR(alt_state);
  KRML_MAYBE_UNUSED_VAR(uids);
  return TauFairScheduler_count_prefill_aux(total_kvs, fair_shares, n, 0);
}

Prims_list__krml_checked_int_t
*TauFairScheduler_check_decode_deadlines(
  TauFairScheduler_alt_history_state alt_state,
  Prims_list__krml_checked_int_t *deadlines_us,
  krml_checked_int_t n,
  krml_checked_int_t now_us
)
{
  KRML_MAYBE_UNUSED_VAR(alt_state);
  return
    TauFairScheduler_check_decode_deadlines_aux(deadlines_us,
      n,
      now_us,
      0,
      FStar_Seq_Base_create__krml_checked_int_t(n, 0));
}

krml_checked_int_t
TauFairScheduler_update_headroom(
  TauFairScheduler_alt_history_state alt_state,
  krml_checked_int_t old_headroom_us,
  bool was_prefill,
  krml_checked_int_t prefill_cost_us,
  bool was_decode,
  krml_checked_int_t delta_decode_iso_us,
  krml_checked_int_t delta_decode_mt_us,
  bool was_idle
)
{
  KRML_MAYBE_UNUSED_VAR(alt_state);
  krml_checked_int_t h0 = old_headroom_us;
  krml_checked_int_t h1;
  if (was_prefill)
    h1 = Prims_op_Subtraction(h0, prefill_cost_us);
  else
    h1 = h0;
  krml_checked_int_t h2;
  if (was_decode)
    h2 = Prims_op_Subtraction(Prims_op_Addition(h1, delta_decode_iso_us), delta_decode_mt_us);
  else
    h2 = h1;
  krml_checked_int_t h3;
  if (was_idle)
    h3 = Prims_op_Addition(h2, delta_decode_iso_us);
  else
    h3 = h2;
  if (Prims_op_GreaterThanOrEqual(h3, 0))
    return h3;
  else
    return 0;
}

bool
TauFairScheduler_can_admit_request(
  TauFairScheduler_alt_history_state alt_state,
  Prims_string uid,
  krml_checked_int_t needed_tokens,
  krml_checked_int_t total_kv,
  krml_checked_int_t evictable_kv,
  krml_checked_int_t fair_share,
  krml_checked_int_t reservation,
  krml_checked_int_t global_slack,
  bool cache_has_space
)
{
  KRML_MAYBE_UNUSED_VAR(alt_state);
  KRML_MAYBE_UNUSED_VAR(uid);
  return
    cache_has_space ||
      Prims_op_LessThanOrEqual(Prims_op_Addition(total_kv, needed_tokens),
        fair_share)
    ||
      Prims_op_LessThanOrEqual(Prims_op_Addition(total_kv, needed_tokens), reservation) &&
        Prims_op_GreaterThanOrEqual(evictable_kv,
          needed_tokens)
    || Prims_op_GreaterThanOrEqual(global_slack, needed_tokens);
}

krml_checked_int_t
TauFairScheduler_compute_global_slack(
  TauFairScheduler_alt_history_state alt_state,
  Prims_list__krml_checked_int_t *total_kvs,
  krml_checked_int_t n,
  krml_checked_int_t max_kv
)
{
  KRML_MAYBE_UNUSED_VAR(alt_state);
  krml_checked_int_t sum_kv = TauFairScheduler_sum_aux(total_kvs, n, 0);
  if (Prims_op_GreaterThanOrEqual(max_kv, sum_kv))
    return Prims_op_Subtraction(max_kv, sum_kv);
  else
    return 0;
}

krml_checked_int_t
TauFairScheduler_isolated_prefill_latency(
  krml_checked_int_t prompt_len,
  krml_checked_int_t max_tok,
  krml_checked_int_t req_count,
  TauFairScheduler_perf_coeffs coeffs,
  krml_checked_int_t num_clients
)
{
  krml_checked_int_t term1 = TauFairScheduler_mul(coeffs.alpha_p_nspt, prompt_len, 0);
  krml_checked_int_t term2 = TauFairScheduler_mul(coeffs.beta_p_nspt, max_tok, 0);
  krml_checked_int_t term3 = TauFairScheduler_mul(coeffs.gamma_p_nspt, req_count, 0);
  krml_checked_int_t
  inner =
    Prims_op_Addition(Prims_op_Addition(Prims_op_Addition(coeffs.cp_ns, term1), term2),
      term3);
  krml_checked_int_t prod = TauFairScheduler_mul(num_clients, inner, 0);
  return Prims_op_Division(prod, 1000);
}

krml_checked_int_t
TauFairScheduler_isolated_decode_latency(
  krml_checked_int_t sum_tok,
  krml_checked_int_t max_tok,
  krml_checked_int_t req_count,
  TauFairScheduler_perf_coeffs coeffs,
  krml_checked_int_t num_clients
)
{
  krml_checked_int_t term1 = TauFairScheduler_mul(coeffs.alpha_d_nspt, sum_tok, 0);
  krml_checked_int_t term2 = TauFairScheduler_mul(coeffs.beta_d_nspt, max_tok, 0);
  krml_checked_int_t term3 = TauFairScheduler_mul(coeffs.gamma_d_nspt, req_count, 0);
  krml_checked_int_t
  inner =
    Prims_op_Addition(Prims_op_Addition(Prims_op_Addition(coeffs.cd_ns, term1), term2),
      term3);
  krml_checked_int_t prod = TauFairScheduler_mul(num_clients, inner, 0);
  return Prims_op_Division(prod, 1000);
}

krml_checked_int_t
TauFairScheduler_mt_decode_latency(
  krml_checked_int_t sum_tok,
  krml_checked_int_t max_tok,
  krml_checked_int_t req_count,
  TauFairScheduler_perf_coeffs coeffs
)
{
  krml_checked_int_t term1 = TauFairScheduler_mul(coeffs.alpha_d_nspt, sum_tok, 0);
  krml_checked_int_t term2 = TauFairScheduler_mul(coeffs.beta_d_nspt, max_tok, 0);
  krml_checked_int_t term3 = TauFairScheduler_mul(coeffs.gamma_d_nspt, req_count, 0);
  return
    Prims_op_Division(Prims_op_Addition(Prims_op_Addition(Prims_op_Addition(coeffs.cd_ns, term1),
          term2),
        term3),
      1000);
}

krml_checked_int_t
TauFairScheduler_compute_headroom(
  krml_checked_int_t delta_decode_iso_us,
  krml_checked_int_t delta_decode_mt_us
)
{
  return Prims_op_Subtraction(delta_decode_iso_us, delta_decode_mt_us);
}

TauFairScheduler_tau_breakdown
TauFairScheduler_split_tau(
  krml_checked_int_t tau_us,
  krml_checked_int_t cache_ratio_bps,
  krml_checked_int_t tau_decode_fixed_us
)
{
  krml_checked_int_t tau_prod = TauFairScheduler_mul(tau_us, cache_ratio_bps, 0);
  krml_checked_int_t tau_cache = Prims_op_Division(tau_prod, 10000);
  return
    (
      (TauFairScheduler_tau_breakdown){
        .tau_us = tau_us,
        .tau_cache_us = tau_cache,
        .tau_prefill_us = Prims_op_Subtraction(tau_us, tau_cache),
        .tau_decode_us = tau_decode_fixed_us
      }
    );
}

krml_checked_int_t TauFairScheduler_compute_new_req_ant_type(TauFairScheduler_alt_req req)
{
  KRML_MAYBE_UNUSED_VAR(req);
  return 0;
}

krml_checked_int_t TauFairScheduler_compute_prefill_done_ant_type(TauFairScheduler_alt_req req)
{
  KRML_MAYBE_UNUSED_VAR(req);
  return 1;
}

krml_checked_int_t TauFairScheduler_compute_decode_done_ant_type(TauFairScheduler_alt_req req)
{
  if (Prims_op_LessThan(req.decode_count, req.completion_len))
    return 1;
  else
    return -1;
}

krml_checked_int_t
TauFairScheduler_compute_ant_prefill_end_us(
  krml_checked_int_t arrival_time_us,
  krml_checked_int_t iso_prefill_time_us
)
{
  return Prims_op_Addition(arrival_time_us, iso_prefill_time_us);
}

krml_checked_int_t
TauFairScheduler_compute_ant_decode_end_us(
  krml_checked_int_t previous_ant_end_us,
  krml_checked_int_t iso_decode_time_us
)
{
  return Prims_op_Addition(previous_ant_end_us, iso_decode_time_us);
}

krml_checked_int_t
TauFairScheduler_compute_deadline_from_ant(
  krml_checked_int_t ant_end_ts_us,
  krml_checked_int_t tau_applied_us
)
{
  return Prims_op_Addition(ant_end_ts_us, tau_applied_us);
}

static Prims_list__TauFairScheduler_user_status *empty__TauFairScheduler_user_status(void)
{
  Prims_list__TauFairScheduler_user_status
  *buf = KRML_HOST_MALLOC(sizeof (Prims_list__TauFairScheduler_user_status));
  if (buf != NULL)
    buf[0U] = ((Prims_list__TauFairScheduler_user_status){ .tag = Prims_Nil });
  return buf;
}

static Prims_list__TauFairScheduler_token_deadline
*empty__TauFairScheduler_token_deadline(void)
{
  Prims_list__TauFairScheduler_token_deadline
  *buf = KRML_HOST_MALLOC(sizeof (Prims_list__TauFairScheduler_token_deadline));
  if (buf != NULL)
    buf[0U] = ((Prims_list__TauFairScheduler_token_deadline){ .tag = Prims_Nil });
  return buf;
}

TauFairScheduler_alt_history_state
TauFairScheduler_alt_history_init(
  krml_checked_int_t num_users,
  krml_checked_int_t start_time_us,
  krml_checked_int_t max_kv
)
{
  return
    (
      (TauFairScheduler_alt_history_state){
        .current_time_us = start_time_us,
        .num_users = num_users,
        .max_kv = max_kv,
        .users = empty__TauFairScheduler_user_status(),
        .n_users = 0,
        .deadlines = empty__TauFairScheduler_token_deadline(),
        .n_deadlines = 0
      }
    );
}

Prims_list__TauFairScheduler_alt_req
*FStar_List_Tot_Base_append__TauFairScheduler_alt_req(
  Prims_list__TauFairScheduler_alt_req *x,
  Prims_list__TauFairScheduler_alt_req *y
)
{
  if (x->tag == Prims_Nil)
    return y;
  else if (x->tag == Prims_Cons)
  {
    Prims_list__TauFairScheduler_alt_req *tl1 = x->tl;
    TauFairScheduler_alt_req a1 = x->hd;
    Prims_list__TauFairScheduler_alt_req
    *buf = KRML_HOST_MALLOC(sizeof (Prims_list__TauFairScheduler_alt_req));
    if (buf != NULL)
      buf[0U] =
        (
          (Prims_list__TauFairScheduler_alt_req){
            .tag = Prims_Cons,
            .hd = a1,
            .tl = FStar_List_Tot_Base_append__TauFairScheduler_alt_req(tl1, y)
          }
        );
    return buf;
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

static Prims_list__TauFairScheduler_alt_req
*append__TauFairScheduler_alt_req(
  Prims_list__TauFairScheduler_alt_req *s1,
  Prims_list__TauFairScheduler_alt_req *s2
)
{
  return FStar_List_Tot_Base_append__TauFairScheduler_alt_req(s1, s2);
}

static Prims_list__TauFairScheduler_alt_req
*_cons__TauFairScheduler_alt_req(
  TauFairScheduler_alt_req x,
  Prims_list__TauFairScheduler_alt_req *s
)
{
  Prims_list__TauFairScheduler_alt_req
  *buf = KRML_HOST_MALLOC(sizeof (Prims_list__TauFairScheduler_alt_req));
  if (buf != NULL)
    buf[0U] = ((Prims_list__TauFairScheduler_alt_req){ .tag = Prims_Cons, .hd = x, .tl = s });
  return buf;
}

Prims_list__TauFairScheduler_alt_req
*FStar_Seq_Base_create__TauFairScheduler_alt_req(
  krml_checked_int_t len,
  TauFairScheduler_alt_req v
)
{
  if (len == 0)
  {
    Prims_list__TauFairScheduler_alt_req
    *buf = KRML_HOST_MALLOC(sizeof (Prims_list__TauFairScheduler_alt_req));
    if (buf != NULL)
      buf[0U] = ((Prims_list__TauFairScheduler_alt_req){ .tag = Prims_Nil });
    return buf;
  }
  else
    return
      _cons__TauFairScheduler_alt_req(v,
        FStar_Seq_Base_create__TauFairScheduler_alt_req(Prims_op_Subtraction(len, 1), v));
}

static Prims_list__TauFairScheduler_alt_req
*cons__TauFairScheduler_alt_req(
  TauFairScheduler_alt_req x,
  Prims_list__TauFairScheduler_alt_req *s
)
{
  return
    append__TauFairScheduler_alt_req(FStar_Seq_Base_create__TauFairScheduler_alt_req(1, x),
      s);
}

static Prims_list__TauFairScheduler_alt_req *empty__TauFairScheduler_alt_req(void)
{
  Prims_list__TauFairScheduler_alt_req
  *buf = KRML_HOST_MALLOC(sizeof (Prims_list__TauFairScheduler_alt_req));
  if (buf != NULL)
    buf[0U] = ((Prims_list__TauFairScheduler_alt_req){ .tag = Prims_Nil });
  return buf;
}

Prims_list__TauFairScheduler_user_status
*FStar_List_Tot_Base_append__TauFairScheduler_user_status(
  Prims_list__TauFairScheduler_user_status *x,
  Prims_list__TauFairScheduler_user_status *y
)
{
  if (x->tag == Prims_Nil)
    return y;
  else if (x->tag == Prims_Cons)
  {
    Prims_list__TauFairScheduler_user_status *tl1 = x->tl;
    TauFairScheduler_user_status a1 = x->hd;
    Prims_list__TauFairScheduler_user_status
    *buf = KRML_HOST_MALLOC(sizeof (Prims_list__TauFairScheduler_user_status));
    if (buf != NULL)
      buf[0U] =
        (
          (Prims_list__TauFairScheduler_user_status){
            .tag = Prims_Cons,
            .hd = a1,
            .tl = FStar_List_Tot_Base_append__TauFairScheduler_user_status(tl1, y)
          }
        );
    return buf;
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

static Prims_list__TauFairScheduler_user_status
*append__TauFairScheduler_user_status(
  Prims_list__TauFairScheduler_user_status *s1,
  Prims_list__TauFairScheduler_user_status *s2
)
{
  return FStar_List_Tot_Base_append__TauFairScheduler_user_status(s1, s2);
}

static Prims_list__TauFairScheduler_user_status
*_cons__TauFairScheduler_user_status(
  TauFairScheduler_user_status x,
  Prims_list__TauFairScheduler_user_status *s
)
{
  Prims_list__TauFairScheduler_user_status
  *buf = KRML_HOST_MALLOC(sizeof (Prims_list__TauFairScheduler_user_status));
  if (buf != NULL)
    buf[0U] = ((Prims_list__TauFairScheduler_user_status){ .tag = Prims_Cons, .hd = x, .tl = s });
  return buf;
}

Prims_list__TauFairScheduler_user_status
*FStar_Seq_Base_create__TauFairScheduler_user_status(
  krml_checked_int_t len,
  TauFairScheduler_user_status v
)
{
  if (len == 0)
  {
    Prims_list__TauFairScheduler_user_status
    *buf = KRML_HOST_MALLOC(sizeof (Prims_list__TauFairScheduler_user_status));
    if (buf != NULL)
      buf[0U] = ((Prims_list__TauFairScheduler_user_status){ .tag = Prims_Nil });
    return buf;
  }
  else
    return
      _cons__TauFairScheduler_user_status(v,
        FStar_Seq_Base_create__TauFairScheduler_user_status(Prims_op_Subtraction(len, 1), v));
}

static Prims_list__TauFairScheduler_user_status
*snoc__TauFairScheduler_user_status(
  Prims_list__TauFairScheduler_user_status *s,
  TauFairScheduler_user_status x
)
{
  return
    append__TauFairScheduler_user_status(s,
      FStar_Seq_Base_create__TauFairScheduler_user_status(1, x));
}

Prims_list__TauFairScheduler_token_deadline
*FStar_List_Tot_Base_append__TauFairScheduler_token_deadline(
  Prims_list__TauFairScheduler_token_deadline *x,
  Prims_list__TauFairScheduler_token_deadline *y
)
{
  if (x->tag == Prims_Nil)
    return y;
  else if (x->tag == Prims_Cons)
  {
    Prims_list__TauFairScheduler_token_deadline *tl1 = x->tl;
    TauFairScheduler_token_deadline a1 = x->hd;
    Prims_list__TauFairScheduler_token_deadline
    *buf = KRML_HOST_MALLOC(sizeof (Prims_list__TauFairScheduler_token_deadline));
    if (buf != NULL)
      buf[0U] =
        (
          (Prims_list__TauFairScheduler_token_deadline){
            .tag = Prims_Cons,
            .hd = a1,
            .tl = FStar_List_Tot_Base_append__TauFairScheduler_token_deadline(tl1, y)
          }
        );
    return buf;
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

static Prims_list__TauFairScheduler_token_deadline
*append__TauFairScheduler_token_deadline(
  Prims_list__TauFairScheduler_token_deadline *s1,
  Prims_list__TauFairScheduler_token_deadline *s2
)
{
  return FStar_List_Tot_Base_append__TauFairScheduler_token_deadline(s1, s2);
}

static Prims_list__TauFairScheduler_token_deadline
*_cons__TauFairScheduler_token_deadline(
  TauFairScheduler_token_deadline x,
  Prims_list__TauFairScheduler_token_deadline *s
)
{
  Prims_list__TauFairScheduler_token_deadline
  *buf = KRML_HOST_MALLOC(sizeof (Prims_list__TauFairScheduler_token_deadline));
  if (buf != NULL)
    buf[0U] =
      ((Prims_list__TauFairScheduler_token_deadline){ .tag = Prims_Cons, .hd = x, .tl = s });
  return buf;
}

Prims_list__TauFairScheduler_token_deadline
*FStar_Seq_Base_create__TauFairScheduler_token_deadline(
  krml_checked_int_t len,
  TauFairScheduler_token_deadline v
)
{
  if (len == 0)
  {
    Prims_list__TauFairScheduler_token_deadline
    *buf = KRML_HOST_MALLOC(sizeof (Prims_list__TauFairScheduler_token_deadline));
    if (buf != NULL)
      buf[0U] = ((Prims_list__TauFairScheduler_token_deadline){ .tag = Prims_Nil });
    return buf;
  }
  else
    return
      _cons__TauFairScheduler_token_deadline(v,
        FStar_Seq_Base_create__TauFairScheduler_token_deadline(Prims_op_Subtraction(len, 1), v));
}

static Prims_list__TauFairScheduler_token_deadline
*snoc__TauFairScheduler_token_deadline(
  Prims_list__TauFairScheduler_token_deadline *s,
  TauFairScheduler_token_deadline x
)
{
  return
    append__TauFairScheduler_token_deadline(s,
      FStar_Seq_Base_create__TauFairScheduler_token_deadline(1, x));
}

TauFairScheduler_alt_history_state
TauFairScheduler_alt_history_push_request(
  TauFairScheduler_alt_history_state state,
  Prims_string rid,
  Prims_string uid,
  krml_checked_int_t prompt_len,
  krml_checked_int_t completion_len,
  krml_checked_int_t arrival_time_us,
  TauFairScheduler_perf_coeffs coeffs,
  TauFairScheduler_tau_breakdown tb
)
{
  krml_checked_int_t
  iso_prefill = TauFairScheduler_isolated_prefill_latency(prompt_len, 0, 1, coeffs, 1);
  krml_checked_int_t iso_decode = TauFairScheduler_isolated_decode_latency(1, 0, 1, coeffs, 1);
  krml_checked_int_t
  ant_end = TauFairScheduler_compute_ant_prefill_end_us(arrival_time_us, iso_prefill);
  krml_checked_int_t
  deadline_us = TauFairScheduler_compute_deadline_from_ant(ant_end, tb.tau_prefill_us);
  TauFairScheduler_alt_req
  new_req =
    {
      .rid1 = rid, .uid1 = uid, .prompt_len = prompt_len, .completion_len = completion_len,
      .status = 0, .decode_count = 0, .arrival_time_us = arrival_time_us,
      .iso_prefill_time_us = iso_prefill, .iso_decode_time_us = iso_decode, .ant_type = 0,
      .ant_end_ts_us = ant_end
    };
  TauFairScheduler_token_deadline
  deadline =
    {
      .rid = rid, .uid = uid, .token_index = 0, .iso_latency_us = iso_prefill,
      .tau_applied_us = tb.tau_prefill_us, .deadline_us = deadline_us
    };
  TauFairScheduler_user_status
  new_user =
    {
      .uid2 = uid,
      .requests = cons__TauFairScheduler_alt_req(new_req, empty__TauFairScheduler_alt_req()),
      .n_requests = 1
    };
  return
    (
      (TauFairScheduler_alt_history_state){
        .current_time_us = state.current_time_us,
        .num_users = state.num_users,
        .max_kv = state.max_kv,
        .users = snoc__TauFairScheduler_user_status(state.users, new_user),
        .n_users = Prims_op_Addition(state.n_users, 1),
        .deadlines = snoc__TauFairScheduler_token_deadline(state.deadlines, deadline),
        .n_deadlines = Prims_op_Addition(state.n_deadlines, 1)
      }
    );
}

TauFairScheduler_alt_history_state
TauFairScheduler_alt_history_advance(
  TauFairScheduler_alt_history_state state,
  TauFairScheduler_perf_coeffs coeffs,
  TauFairScheduler_tau_breakdown tb
)
{
  KRML_MAYBE_UNUSED_VAR(coeffs);
  KRML_MAYBE_UNUSED_VAR(tb);
  return
    (
      (TauFairScheduler_alt_history_state){
        .current_time_us = Prims_op_Addition(state.current_time_us, 1),
        .num_users = state.num_users,
        .max_kv = state.max_kv,
        .users = state.users,
        .n_users = state.n_users,
        .deadlines = state.deadlines,
        .n_deadlines = state.n_deadlines
      }
    );
}

Prims_list__TauFairScheduler_token_deadline
*TauFairScheduler_alt_history_extract_deadlines(TauFairScheduler_alt_history_state state)
{
  return state.deadlines;
}

TauFairScheduler_alt_history_state
TauFairScheduler_alt_history_complete_request(
  TauFairScheduler_alt_history_state state,
  Prims_string rid
)
{
  KRML_MAYBE_UNUSED_VAR(rid);
  return state;
}

TauFairScheduler_alt_history_state
TauFairScheduler_alt_history_reconcile(
  TauFairScheduler_alt_history_state state,
  krml_checked_int_t real_time_us,
  Prims_list__Prims_string *completed_rids,
  krml_checked_int_t n_completed
)
{
  KRML_MAYBE_UNUSED_VAR(completed_rids);
  KRML_MAYBE_UNUSED_VAR(n_completed);
  return
    (
      (TauFairScheduler_alt_history_state){
        .current_time_us = real_time_us,
        .num_users = state.num_users,
        .max_kv = state.max_kv,
        .users = state.users,
        .n_users = state.n_users,
        .deadlines = state.deadlines,
        .n_deadlines = state.n_deadlines
      }
    );
}

krml_checked_int_t
TauFairScheduler_alt_history_get_user_token_count(
  TauFairScheduler_alt_history_state state,
  Prims_string uid
)
{
  KRML_MAYBE_UNUSED_VAR(state);
  KRML_MAYBE_UNUSED_VAR(uid);
  return 0;
}

