/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: krml /workspace/TauFairScheduler.fst -tmpdir /tmp/c_out -skip-compilation -warn-error -2
  F* version: <unknown>
  KaRaMeL version: 3611ae497bb5ab8ae83207428c8a915653bd761c
 */

#ifndef TauFairScheduler_H
#define TauFairScheduler_H

#include "krmllib.h"

typedef struct TauFairScheduler_perf_coeffs_s
{
  krml_checked_int_t cp_ns;
  krml_checked_int_t alpha_p_nspt;
  krml_checked_int_t beta_p_nspt;
  krml_checked_int_t gamma_p_nspt;
  krml_checked_int_t cd_ns;
  krml_checked_int_t alpha_d_nspt;
  krml_checked_int_t beta_d_nspt;
  krml_checked_int_t gamma_d_nspt;
}
TauFairScheduler_perf_coeffs;

typedef struct TauFairScheduler_tau_breakdown_s
{
  krml_checked_int_t tau_us;
  krml_checked_int_t tau_cache_us;
  krml_checked_int_t tau_prefill_us;
  krml_checked_int_t tau_decode_us;
}
TauFairScheduler_tau_breakdown;

typedef struct TauFairScheduler_token_deadline_s
{
  Prims_string rid;
  Prims_string uid;
  krml_checked_int_t token_index;
  krml_checked_int_t iso_latency_us;
  krml_checked_int_t tau_applied_us;
  krml_checked_int_t deadline_us;
}
TauFairScheduler_token_deadline;

typedef struct TauFairScheduler_alt_req_s
{
  Prims_string rid1;
  Prims_string uid1;
  krml_checked_int_t prompt_len;
  krml_checked_int_t completion_len;
  krml_checked_int_t status;
  krml_checked_int_t decode_count;
  krml_checked_int_t arrival_time_us;
  krml_checked_int_t iso_prefill_time_us;
  krml_checked_int_t iso_decode_time_us;
  krml_checked_int_t ant_type;
  krml_checked_int_t ant_end_ts_us;
}
TauFairScheduler_alt_req;

typedef struct Prims_list__TauFairScheduler_alt_req_s Prims_list__TauFairScheduler_alt_req;

#define Prims_Nil 0
#define Prims_Cons 1

typedef uint8_t Prims_list__TauFairScheduler_alt_req_tags;

typedef struct Prims_list__TauFairScheduler_alt_req_s
{
  Prims_list__TauFairScheduler_alt_req_tags tag;
  TauFairScheduler_alt_req hd;
  Prims_list__TauFairScheduler_alt_req *tl;
}
Prims_list__TauFairScheduler_alt_req;

typedef struct TauFairScheduler_user_status_s
{
  Prims_string uid2;
  Prims_list__TauFairScheduler_alt_req *requests;
  krml_checked_int_t n_requests;
}
TauFairScheduler_user_status;

typedef struct Prims_list__TauFairScheduler_user_status_s
Prims_list__TauFairScheduler_user_status;

typedef struct Prims_list__TauFairScheduler_user_status_s
{
  Prims_list__TauFairScheduler_alt_req_tags tag;
  TauFairScheduler_user_status hd;
  Prims_list__TauFairScheduler_user_status *tl;
}
Prims_list__TauFairScheduler_user_status;

typedef struct Prims_list__TauFairScheduler_token_deadline_s
Prims_list__TauFairScheduler_token_deadline;

typedef struct Prims_list__TauFairScheduler_token_deadline_s
{
  Prims_list__TauFairScheduler_alt_req_tags tag;
  TauFairScheduler_token_deadline hd;
  Prims_list__TauFairScheduler_token_deadline *tl;
}
Prims_list__TauFairScheduler_token_deadline;

typedef struct TauFairScheduler_alt_history_state_s
{
  krml_checked_int_t current_time_us;
  krml_checked_int_t num_users;
  krml_checked_int_t max_kv;
  Prims_list__TauFairScheduler_user_status *users;
  krml_checked_int_t n_users;
  Prims_list__TauFairScheduler_token_deadline *deadlines;
  krml_checked_int_t n_deadlines;
}
TauFairScheduler_alt_history_state;

typedef struct TauFairScheduler_sched_req_s
{
  Prims_string rid2;
  Prims_string uid3;
  krml_checked_int_t prompt_len1;
  krml_checked_int_t max_new_tok;
  krml_checked_int_t deadline_us1;
  bool is_running;
  bool is_finished;
}
TauFairScheduler_sched_req;

typedef struct Prims_list__TauFairScheduler_sched_req_s Prims_list__TauFairScheduler_sched_req;

typedef struct Prims_list__TauFairScheduler_sched_req_s
{
  Prims_list__TauFairScheduler_alt_req_tags tag;
  TauFairScheduler_sched_req hd;
  Prims_list__TauFairScheduler_sched_req *tl;
}
Prims_list__TauFairScheduler_sched_req;

typedef struct TauFairScheduler_sched_batch_s
{
  Prims_list__TauFairScheduler_sched_req *reqs;
  krml_checked_int_t sum_tok;
  krml_checked_int_t max_tok;
  krml_checked_int_t req_count;
  bool is_prefill;
  bool is_empty;
}
TauFairScheduler_sched_batch;

typedef struct TauFairScheduler_fair_share_state_s
{
  Prims_string uid4;
  krml_checked_int_t total_kv;
  krml_checked_int_t evictable_kv;
  krml_checked_int_t fair_share;
  krml_checked_int_t reservation;
  krml_checked_int_t pending_prefills;
  krml_checked_int_t running_decodes;
  krml_checked_int_t last_decode_ts_us;
  krml_checked_int_t last_prefill_ts_us;
}
TauFairScheduler_fair_share_state;

typedef struct TauFairScheduler_e_d_f_ordering_key_s
{
  krml_checked_int_t tier;
  krml_checked_int_t neg_shortfall;
  krml_checked_int_t excess;
}
TauFairScheduler_e_d_f_ordering_key;

krml_checked_int_t
TauFairScheduler_mul(krml_checked_int_t a, krml_checked_int_t b, krml_checked_int_t acc);

typedef struct Prims_list__krml_checked_int_t_s Prims_list__krml_checked_int_t;

typedef struct Prims_list__krml_checked_int_t_s
{
  Prims_list__TauFairScheduler_alt_req_tags tag;
  krml_checked_int_t hd;
  Prims_list__krml_checked_int_t *tl;
}
Prims_list__krml_checked_int_t;

bool
TauFairScheduler_would_violate_aux(
  Prims_list__krml_checked_int_t *running_deadlines_us,
  krml_checked_int_t threshold,
  krml_checked_int_t i,
  krml_checked_int_t n_running
);

Prims_list__krml_checked_int_t
*TauFairScheduler_gen_range(krml_checked_int_t n, krml_checked_int_t i);

Prims_list__krml_checked_int_t
*TauFairScheduler_remove_elem(Prims_list__krml_checked_int_t *s, krml_checked_int_t v);

krml_checked_int_t
TauFairScheduler_warn_overdue_aux(
  Prims_list__krml_checked_int_t *deadlines_us,
  krml_checked_int_t n,
  krml_checked_int_t now_us,
  krml_checked_int_t i
);

krml_checked_int_t
TauFairScheduler_count_prefill_aux(
  Prims_list__krml_checked_int_t *total_kvs,
  Prims_list__krml_checked_int_t *fair_shares,
  krml_checked_int_t n,
  krml_checked_int_t i
);

Prims_list__krml_checked_int_t
*TauFairScheduler_check_decode_deadlines_aux(
  Prims_list__krml_checked_int_t *deadlines_us,
  krml_checked_int_t n,
  krml_checked_int_t now_us,
  krml_checked_int_t i,
  Prims_list__krml_checked_int_t *acc
);

krml_checked_int_t
TauFairScheduler_sum_aux(
  Prims_list__krml_checked_int_t *total_kvs,
  krml_checked_int_t n,
  krml_checked_int_t i
);

TauFairScheduler_e_d_f_ordering_key
TauFairScheduler_edf_fairshare_key(
  krml_checked_int_t deadline_us,
  krml_checked_int_t total_kv,
  krml_checked_int_t fair_share,
  krml_checked_int_t tau_us,
  krml_checked_int_t now_us
);

bool
TauFairScheduler_edf_compare(
  TauFairScheduler_e_d_f_ordering_key a,
  TauFairScheduler_e_d_f_ordering_key b
);

bool
TauFairScheduler_is_well_behaved(krml_checked_int_t total_kv, krml_checked_int_t fair_share);

bool
TauFairScheduler_is_over_quota(krml_checked_int_t total_kv, krml_checked_int_t fair_share);

bool
TauFairScheduler_is_within_reservation(
  krml_checked_int_t total_kv,
  krml_checked_int_t reservation
);

krml_checked_int_t
TauFairScheduler_unevictable_tokens(
  krml_checked_int_t total_kv,
  krml_checked_int_t evictable_kv
);

krml_checked_int_t
TauFairScheduler_eviction_spare(krml_checked_int_t total_kv, krml_checked_int_t reservation);

krml_checked_int_t
TauFairScheduler_on_new_request_init_deadline(
  TauFairScheduler_alt_history_state alt_state,
  Prims_string uid,
  krml_checked_int_t prompt_len,
  krml_checked_int_t completion_len,
  krml_checked_int_t iso_prefill_time_us,
  krml_checked_int_t tau_cache_us,
  krml_checked_int_t tau_prefill_us,
  krml_checked_int_t now_us
);

bool
TauFairScheduler_would_violate_decode_deadlines(
  TauFairScheduler_alt_history_state alt_state,
  krml_checked_int_t prefill_cost_us,
  krml_checked_int_t headroom_us,
  Prims_list__krml_checked_int_t *running_deadlines_us,
  krml_checked_int_t n_running,
  krml_checked_int_t delta_decode_mt_us,
  krml_checked_int_t now_us
);

krml_checked_int_t
TauFairScheduler_prefill_vs_decode_decision(
  TauFairScheduler_alt_history_state alt_state,
  Prims_list__krml_checked_int_t *running_deadlines_us,
  krml_checked_int_t n_running,
  bool has_candidate_prefill,
  krml_checked_int_t prefill_cost_us,
  krml_checked_int_t accumulated_headroom_us,
  krml_checked_int_t delta_decode_mt_us,
  krml_checked_int_t tau_us,
  krml_checked_int_t now_us,
  bool any_over_quota,
  bool any_starved,
  bool max_per_user_active
);

TauFairScheduler_e_d_f_ordering_key
TauFairScheduler_key_of(
  Prims_list__krml_checked_int_t *deadlines_us,
  Prims_list__krml_checked_int_t *total_kvs,
  Prims_list__krml_checked_int_t *fair_shares,
  krml_checked_int_t tau_us,
  krml_checked_int_t now_us,
  krml_checked_int_t i
);

krml_checked_int_t
TauFairScheduler_find_min(
  Prims_list__krml_checked_int_t *deadlines_us,
  Prims_list__krml_checked_int_t *total_kvs,
  Prims_list__krml_checked_int_t *fair_shares,
  krml_checked_int_t tau_us,
  krml_checked_int_t now_us,
  Prims_list__krml_checked_int_t *s
);

Prims_list__krml_checked_int_t
*TauFairScheduler_sort_aux(
  Prims_list__krml_checked_int_t *deadlines_us,
  Prims_list__krml_checked_int_t *total_kvs,
  Prims_list__krml_checked_int_t *fair_shares,
  krml_checked_int_t tau_us,
  krml_checked_int_t now_us,
  Prims_list__krml_checked_int_t *s,
  Prims_list__krml_checked_int_t *acc
);

typedef struct Prims_list__Prims_string_s Prims_list__Prims_string;

typedef struct Prims_list__Prims_string_s
{
  Prims_list__TauFairScheduler_alt_req_tags tag;
  Prims_string hd;
  Prims_list__Prims_string *tl;
}
Prims_list__Prims_string;

Prims_list__krml_checked_int_t
*TauFairScheduler_sort_prefill_queue(
  TauFairScheduler_alt_history_state alt_state,
  Prims_list__krml_checked_int_t *deadlines_us,
  Prims_list__Prims_string *uids,
  Prims_list__krml_checked_int_t *total_kvs,
  Prims_list__krml_checked_int_t *fair_shares,
  krml_checked_int_t n,
  krml_checked_int_t tau_us,
  krml_checked_int_t now_us
);

krml_checked_int_t
TauFairScheduler_warn_overdue_deadlines(
  TauFairScheduler_alt_history_state alt_state,
  Prims_list__krml_checked_int_t *deadlines_us,
  krml_checked_int_t n,
  krml_checked_int_t now_us
);

krml_checked_int_t
TauFairScheduler_count_prefill_admitted(
  TauFairScheduler_alt_history_state alt_state,
  Prims_list__Prims_string *uids,
  Prims_list__krml_checked_int_t *total_kvs,
  Prims_list__krml_checked_int_t *fair_shares,
  krml_checked_int_t n
);

Prims_list__krml_checked_int_t
*TauFairScheduler_check_decode_deadlines(
  TauFairScheduler_alt_history_state alt_state,
  Prims_list__krml_checked_int_t *deadlines_us,
  krml_checked_int_t n,
  krml_checked_int_t now_us
);

krml_checked_int_t
TauFairScheduler_update_headroom(
  TauFairScheduler_alt_history_state alt_state,
  krml_checked_int_t old_headroom_us,
  bool was_prefill,
  krml_checked_int_t prefill_cost_us,
  bool was_decode,
  krml_checked_int_t delta_decode_iso_us,
  krml_checked_int_t delta_decode_mt_us,
  bool was_idle
);

bool
TauFairScheduler_can_admit_request(
  TauFairScheduler_alt_history_state alt_state,
  Prims_string uid,
  krml_checked_int_t needed_tokens,
  krml_checked_int_t total_kv,
  krml_checked_int_t evictable_kv,
  krml_checked_int_t fair_share,
  krml_checked_int_t reservation,
  krml_checked_int_t global_slack,
  bool cache_has_space
);

krml_checked_int_t
TauFairScheduler_compute_global_slack(
  TauFairScheduler_alt_history_state alt_state,
  Prims_list__krml_checked_int_t *total_kvs,
  krml_checked_int_t n,
  krml_checked_int_t max_kv
);

krml_checked_int_t
TauFairScheduler_isolated_prefill_latency(
  krml_checked_int_t prompt_len,
  krml_checked_int_t max_tok,
  krml_checked_int_t req_count,
  TauFairScheduler_perf_coeffs coeffs,
  krml_checked_int_t num_clients
);

krml_checked_int_t
TauFairScheduler_isolated_decode_latency(
  krml_checked_int_t sum_tok,
  krml_checked_int_t max_tok,
  krml_checked_int_t req_count,
  TauFairScheduler_perf_coeffs coeffs,
  krml_checked_int_t num_clients
);

krml_checked_int_t
TauFairScheduler_mt_decode_latency(
  krml_checked_int_t sum_tok,
  krml_checked_int_t max_tok,
  krml_checked_int_t req_count,
  TauFairScheduler_perf_coeffs coeffs
);

krml_checked_int_t
TauFairScheduler_compute_headroom(
  krml_checked_int_t delta_decode_iso_us,
  krml_checked_int_t delta_decode_mt_us
);

TauFairScheduler_tau_breakdown
TauFairScheduler_split_tau(
  krml_checked_int_t tau_us,
  krml_checked_int_t cache_ratio_bps,
  krml_checked_int_t tau_decode_fixed_us
);

krml_checked_int_t TauFairScheduler_compute_new_req_ant_type(TauFairScheduler_alt_req req);

krml_checked_int_t
TauFairScheduler_compute_prefill_done_ant_type(TauFairScheduler_alt_req req);

krml_checked_int_t TauFairScheduler_compute_decode_done_ant_type(TauFairScheduler_alt_req req);

krml_checked_int_t
TauFairScheduler_compute_ant_prefill_end_us(
  krml_checked_int_t arrival_time_us,
  krml_checked_int_t iso_prefill_time_us
);

krml_checked_int_t
TauFairScheduler_compute_ant_decode_end_us(
  krml_checked_int_t previous_ant_end_us,
  krml_checked_int_t iso_decode_time_us
);

krml_checked_int_t
TauFairScheduler_compute_deadline_from_ant(
  krml_checked_int_t ant_end_ts_us,
  krml_checked_int_t tau_applied_us
);

TauFairScheduler_alt_history_state
TauFairScheduler_alt_history_init(
  krml_checked_int_t num_users,
  krml_checked_int_t start_time_us,
  krml_checked_int_t max_kv
);

TauFairScheduler_alt_history_state
TauFairScheduler_alt_history_push_request(
  TauFairScheduler_alt_history_state state,
  Prims_string rid,
  Prims_string uid,
  krml_checked_int_t prompt_len,
  krml_checked_int_t completion_len,
  krml_checked_int_t arrival_time_us,
  TauFairScheduler_perf_coeffs coeffs,
  TauFairScheduler_tau_breakdown tb
);

TauFairScheduler_alt_history_state
TauFairScheduler_alt_history_advance(
  TauFairScheduler_alt_history_state state,
  TauFairScheduler_perf_coeffs coeffs,
  TauFairScheduler_tau_breakdown tb
);

Prims_list__TauFairScheduler_token_deadline
*TauFairScheduler_alt_history_extract_deadlines(TauFairScheduler_alt_history_state state);

TauFairScheduler_alt_history_state
TauFairScheduler_alt_history_complete_request(
  TauFairScheduler_alt_history_state state,
  Prims_string rid
);

TauFairScheduler_alt_history_state
TauFairScheduler_alt_history_reconcile(
  TauFairScheduler_alt_history_state state,
  krml_checked_int_t real_time_us,
  Prims_list__Prims_string *completed_rids,
  krml_checked_int_t n_completed
);

krml_checked_int_t
TauFairScheduler_alt_history_get_user_token_count(
  TauFairScheduler_alt_history_state state,
  Prims_string uid
);


#define TauFairScheduler_H_DEFINED
#endif /* TauFairScheduler_H */
