/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: krml /workspace/DeadlineModel.fst -tmpdir /tmp/c_out -skip-compilation -warn-error -2
  F* version: <unknown>
  KaRaMeL version: 3611ae497bb5ab8ae83207428c8a915653bd761c
 */

#ifndef internal_DeadlineModel_H
#define internal_DeadlineModel_H

#include "krmllib.h"

#include "../DeadlineModel.h"

krml_checked_int_t
FStar_List_Tot_Base_index__krml_checked_int_t(
  Prims_list__krml_checked_int_t *l,
  krml_checked_int_t i
);

Prims_list__krml_checked_int_t
*FStar_List_Tot_Base_append__krml_checked_int_t(
  Prims_list__krml_checked_int_t *x,
  Prims_list__krml_checked_int_t *y
);

Prims_list__krml_checked_int_t
*FStar_Seq_Base_create__krml_checked_int_t(krml_checked_int_t len, krml_checked_int_t v);

krml_checked_int_t
FStar_List_Tot_Base_length__krml_checked_int_t(Prims_list__krml_checked_int_t *uu___);

Prims_list__krml_checked_int_t
*FStar_Seq_Base_slice___krml_checked_int_t(
  Prims_list__krml_checked_int_t *s,
  krml_checked_int_t i,
  krml_checked_int_t j
);

Prims_list__krml_checked_int_t
*FStar_Seq_Base_upd___krml_checked_int_t(
  Prims_list__krml_checked_int_t *s,
  krml_checked_int_t n,
  krml_checked_int_t v
);

Prims_list__DeadlineModel_alt_req
*FStar_List_Tot_Base_append__DeadlineModel_alt_req(
  Prims_list__DeadlineModel_alt_req *x,
  Prims_list__DeadlineModel_alt_req *y
);

Prims_list__DeadlineModel_alt_req
*FStar_Seq_Base_create__DeadlineModel_alt_req(krml_checked_int_t len, DeadlineModel_alt_req v);

Prims_list__DeadlineModel_user_status
*FStar_List_Tot_Base_append__DeadlineModel_user_status(
  Prims_list__DeadlineModel_user_status *x,
  Prims_list__DeadlineModel_user_status *y
);

Prims_list__DeadlineModel_user_status
*FStar_Seq_Base_create__DeadlineModel_user_status(
  krml_checked_int_t len,
  DeadlineModel_user_status v
);

Prims_list__DeadlineModel_token_deadline
*FStar_List_Tot_Base_append__DeadlineModel_token_deadline(
  Prims_list__DeadlineModel_token_deadline *x,
  Prims_list__DeadlineModel_token_deadline *y
);

Prims_list__DeadlineModel_token_deadline
*FStar_Seq_Base_create__DeadlineModel_token_deadline(
  krml_checked_int_t len,
  DeadlineModel_token_deadline v
);


#define internal_DeadlineModel_H_DEFINED
#endif /* internal_DeadlineModel_H */
